# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright 2023 Red Hat GmbH
# Author: Alice Frosi <afrosi@redhat.com>

test:
	$(CC) $(CFLAGS) -o test-syscalls test-syscalls.c
	$(CC) $(CFLAGS) -o test-server test-server.c
