# SPDX-License-Identifier: GPL-2.0-or-later
#
# seitan - Syscall Expressive Interpreter, Transformer and Notifier
#
# containerfiles/tests/eater/Containerfile - Containerfile for seitan tests
#
# Copyright (c) 2022-2023 Red Hat GmbH
# Author: Alice Frosi <afrosi@redhat.com>

FROM fedora:37

COPY ./seitan /usr/bin/seitan
COPY ./tests-utils/test-server /usr/local/bin/test-server
