# SPDX-License-Identifier: GPL-2.0-or-later
#
# seitan - Syscall Expressive Interpreter, Transformer and Notifier
#
# containerfiles/tests/eater/Containerfile - Containerfile for eater tests
#
# Copyright (c) 2022-2023 Red Hat GmbH
# Author: Alice Frosi <afrosi@redhat.com>

FROM fedora:37

RUN mkdir -p /var/run/test-filters

COPY ./eater /usr/bin/eater
COPY ./tests-utils/test-syscalls /usr/local/bin/test-syscalls
# Filter without syscalls
COPY ./test.bpf /var/run/test-filters/test.bpf

# Make all test filter files reable by all users
RUN chmod -R 0777 /var/run/test-filters && \
	chmod 0777 /var/run/test-filters/*

ENTRYPOINT ["/usr/bin/eater"]
